<?php

use Overtrue\Wechat\Services\Auth;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-05 at 18:08:22.
 */
class OvertrueWechatServicesAuthTest extends TestCase
{
    /**
     * @var Auth
     */
    protected $object;

     /**
     * @covers Overtrue\Wechat\Services\Auth::url
     * @todo   Implement testUrl().
     */
    public function testUrl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
