<?php

use Overtrue\Wechat\Services\Cache;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-06 at 10:29:09.
 */
class OvertrueWechatServicesCacheTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Cache
     */
    protected $object;

    /**
     * @covers Overtrue\Wechat\Services\Cache::boot
     * @todo   Implement testBoot().
     */
    public function testBoot()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Overtrue\Wechat\Services\Cache::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Overtrue\Wechat\Services\Cache::set
     * @todo   Implement testSet().
     */
    public function testSet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

     /**
     * @covers Overtrue\Wechat\Wechat::cacheWriter
     * @todo   Implement testCacheWriter().
     */
    public function testCacheWriter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Overtrue\Wechat\Wechat::cacheReader
     * @todo   Implement testCacheReader().
     */
    public function testCacheReader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
