<?php

use Overtrue\Wechat\Services\Crypt;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-05 at 18:08:22.
 */
class OvertrueWechatServicesCryptTest extends TestCase
{
    /**
     * @var Crypt
     */
    protected $object;

    /**
     * @covers Overtrue\Wechat\Services\Crypt::hello
     * @todo   Implement testHello().
     */
    public function testHello()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
