<?php

use Overtrue\Wechat\Services\Group;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-05 at 18:08:22.
 */
class OvertrueWechatServicesGroupTest extends TestCase
{
    /**
     * @var Group
     */
    protected $object;

    /**
     * @covers Overtrue\Wechat\Services\Group::create
     * @todo   Implement testCreate().
     */
    public function testCreate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Overtrue\Wechat\Services\Group::update
     * @todo   Implement testUpdate().
     */
    public function testUpdate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Overtrue\Wechat\Services\Group::user
     * @todo   Implement testUser().
     */
    public function testUser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Overtrue\Wechat\Services\Group::users
     * @todo   Implement testUsers().
     */
    public function testUsers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
