<?php

use Overtrue\Wechat\Services\Media;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-05 at 18:08:22.
 */
class OvertrueWechatServicesMediaTest extends TestCase
{
    /**
     * @var Media
     */
    protected $object;

    /**
     * @covers Overtrue\Wechat\Services\Media::upload
     * @todo   Implement testUpload().
     */
    public function testUpload()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Overtrue\Wechat\Services\Media::download
     * @todo   Implement testDownload().
     */
    public function testDownload()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Overtrue\Wechat\Services\Media::__call
     * @todo   Implement test__call().
     */
    public function test__call()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
