<?php

use Overtrue\Wechat\Services\Menu;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-05 at 18:08:23.
 */
class OvertrueWechatServicesMenuTest extends TestCase
{
    /**
     * @var Menu
     */
    protected $object;

    /**
     * @covers Overtrue\Wechat\Services\Menu::create
     * @todo   Implement testCreate().
     */
    public function testCreate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Overtrue\Wechat\Services\Menu::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Overtrue\Wechat\Services\Menu::delete
     * @todo   Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
