<?php

use Overtrue\Wechat\Services\Message;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-05 at 18:08:23.
 */
class OvertrueWechatServicesMessageTest extends TestCase
{
    /**
     * @var Message
     */
    protected $object;


    /**
     * @covers Overtrue\Wechat\Services\Message::make
     * @todo   Implement testMake().
     */
    public function testMake()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Overtrue\Wechat\Services\Message::send
     * @todo   Implement testSend().
     */
    public function testSend()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
