<?php

use Overtrue\Wechat\Services\QRCode;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-05 at 18:08:23.
 */
class OvertrueWechatServicesQRCodeTest extends TestCase
{
    /**
     * @var QRCode
     */
    protected $object;


    /**
     * @covers Overtrue\Wechat\Services\QRCode::create
     * @todo   Implement testCreate().
     */
    public function testCreate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Overtrue\Wechat\Services\QRCode::show
     * @todo   Implement testShow().
     */
    public function testShow()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
