#!/usr/bin/env node

const { default: TenYun } = require('tenyun');

new TenYun(process.env.COS_SECRET_ID ?? '', process.env.COS_SECRET_KEY ?? '')
    .cdn
    .PurgePathCache({
        Paths: [process.env.domain ?? ''],
        FlushType: 'flush',
    })
    .then((data) => console.log(data));
