<?php

use Overtrue\Wechat\Messages\Image;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-05 at 18:11:13.
 */
class OvertrueWechatMessagesImageTest extends TestCase
{
    /**
     * @var Image
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Image;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Overtrue\Wechat\Messages\Image::media
     * @todo   Implement testMedia().
     */
    public function testMedia()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Overtrue\Wechat\Messages\Image::formatToClient
     * @todo   Implement testFormatToClient().
     */
    public function testFormatToClient()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Overtrue\Wechat\Messages\Image::formatToServer
     * @todo   Implement testFormatToServer().
     */
    public function testFormatToServer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
