<?php

use Overtrue\Wechat\Messages\Video;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-05 at 18:08:22.
 */
class OvertrueWechatMessagesVideoTest extends TestCase
{
    /**
     * @var Video
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Video;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Overtrue\Wechat\Messages\Video::media
     * @todo   Implement testMedia().
     */
    public function testMedia()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Overtrue\Wechat\Messages\Video::thumb
     * @todo   Implement testThumb().
     */
    public function testThumb()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Overtrue\Wechat\Messages\Video::formatToClient
     * @todo   Implement testFormatToClient().
     */
    public function testFormatToClient()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Overtrue\Wechat\Messages\Video::formatToServer
     * @todo   Implement testFormatToServer().
     */
    public function testFormatToServer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
