name: Lint
on: [push, pull_request]

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none
      - name: Install Dependencies
        run: composer update -W --prefer-dist --no-interaction
      - name: Run PHPStan
        run: composer phpstan

  pint:
    name: Pint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none
      - name: Install Dependencies
        run: composer update -W --prefer-dist --no-interaction
      - name: Run Pint
        run: composer check-style
