name: Test
on: [push, pull_request]

jobs:
  phpunit:
    name: PHP-${{ matrix.php_version }}-${{ matrix.prefer }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php_version:
          - 8.4
          - 8.5
        prefer:
          - stable
        include:
          - php_version: 8.4
            prefer: lowest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          coverage: none
      - name: Install Dependencies
        run: composer update -W --prefer-dist --no-interaction --prefer-${{ matrix.prefer }}
      - name: Run PHPUnit
        run: composer test
